version: '{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\Kafka.TestFramework.csproj'
  package_version: '{version}'
environment:
  git_access_token:
    secure: V8i7UZRY6IQFpngUi2sgnunCFZKvE4al96flaBKyWqXyRLmTabX0/1Z0Tpl8BWKr
  appveyor_api_token:
    secure: eMpCyScSyam7rRtm3bSRAzt29qATXHWxk8mfgdTpyh0=
install:
- ps: scripts/set-version.ps1
before_build:
- cmd: dotnet restore
build_script:
- dotnet build -c %CONFIGURATION%
test_script:
- dotnet test -c %CONFIGURATION%
after_test:
- ps: >-
    scripts/update-release-notes.ps1

    dotnet pack src/Kafka.TestFramework/Kafka.TestFramework.csproj -c %CONFIGURATION% -o nupkgs
artifacts:
- path: nupkgs\*.nupkg
deploy:
- provider: NuGet
  api_key: 
    secure: CrJHCcuXYVvE4Qwk+1VfIboKDImZyj+NUE5fZQj300ctK0uUCICPgrVNA7YfLRl+
after_deploy:
- ps: scripts/set-version-tag-in-git.ps1