name: Continuous Delivery

on:
  push:
    branches: 
      - '**'

jobs:
  test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

  release:    
    name: Create Release
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Fetches entire history, so we can analyze commits since last tag
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        configFilePath: .github/version_config.yml
    - name: Determine Release Info
      id: release
      run: |
        from_tag=$(git tag --points-at ${{ steps.gitversion.outputs.versionSourceSha }} | grep -m 1 ^v[0-9]*\.[0-9]*\.[0-9]* | head -1)
        [[ -z "$from_tag" ]] && \
          from_ref_exclusive=${{ steps.gitversion.outputs.versionSourceSha }} || \
          from_ref_exclusive=$from_tag

        [[ -z "${{ steps.gitversion.outputs.preReleaseTag }}" ]] && \
          is_prerelease=false || \
          is_prerelease=true

        [[ $is_prerelease == true ]] && \
          version=${{ steps.gitversion.outputs.majorMinorPatch }}-pre-${{ steps.gitversion.outputs.commitsSinceVersionSource }} || \
          version=${{ steps.gitversion.outputs.majorMinorPatch }}

        echo "::set-output name=is_prerelease::$is_prerelease"
        echo "::set-output name=tag::v$version"
        echo "::set-output name=version::$version"
        echo "::set-output name=from_ref_exclusive::$from_ref_exclusive"
    - name: Create Tag
      uses: actions/github-script@v3
      with:
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.release.outputs.tag }}",
            sha: "${{ steps.gitversion.outputs.sha }}"
          });
    - name: Generate Release Notes
      id: release_notes
      uses: Fresa/release-notes-generator@v0
      with:
          version: ${{ steps.release.outputs.tag }}
          from_ref_exclusive: ${{ steps.release.outputs.from_ref_exclusive }}
          to_ref_inclusive: ${{ steps.release.outputs.tag }}
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          tag_name: ${{ steps.release.outputs.tag }}
          prerelease: ${{ steps.release.outputs.is_prerelease }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update Latest Minor Tag
      uses: EndBug/latest-tag@v1
      if: steps.release.outputs.is_prerelease == 'false'
      with:
          tag-name: v${{ steps.gitversion.outputs.major }}
          description: ${{ steps.release.outputs.tag }}
    - name: Update Latest Patch Tag
      uses: EndBug/latest-tag@v1
      if: steps.release.outputs.is_prerelease == 'false'
      with:
          tag-name: v${{ steps.gitversion.outputs.major }}.${{ steps.gitversion.outputs.minor }}
          description: ${{ steps.release.outputs.tag }}
    - name: Pack
      env:
          release_notes: ${{ steps.release_notes.outputs.release_notes }}
      run: dotnet pack Kafka.TestFramework/Kafka.TestFramework.csproj -c Release -o nuget-packages -p:PackageVersion=${{ steps.release.outputs.version }} -p:PackageReleaseNotes="$release_notes"
    - name: Publish to nuget.org
      run: dotnet nuget push nuget-packages/Kafka.TestFramework.${{ steps.release.outputs.version }}.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
